<a href="https://colab.research.google.com/github/azadeh-3880/skills-github-pages/blob/ai-test/Copy_of_untitled5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
from tensorflow import keras
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import numpy as np

#train_test_split*

In [3]:
california_housing=fetch_california_housing()
X_train0,X_test,y_train0,y_test=train_test_split(
                 california_housing["data"],
                 california_housing["target"])

#train_validation_split

In [4]:
california_housing=fetch_california_housing()
X_train1,X_validation,y_train1,y_validation=train_test_split(X_train0,
                                                             y_train0)

In [ ]:
X_test.shape

(5160, 8)

In [ ]:
X_train0.shape

(15480, 8)

In [ ]:
X_validation.shape

(3870, 8)

#normalize

In [5]:
sc=StandardScaler()
X_train_s=sc.fit_transform(X_train1)
X_validation_s=sc.transform(X_validation)
X_test_s=sc.transform(X_test)

#model of NN(layers/activation)

In [ ]:
model=keras.models.Sequential([
    keras.layers.Dense(50,activation="relu"),
    keras.layers.Dense(10,activation="relu"),
    keras.layers.Dense(1)
])

compile

In [ ]:
model.compile(loss="mean_squared_error",
              optimizer="sgd",
              metrics=["mean_absolute_error"]
              )

fit

In [ ]:
model.fit(X_train_s,y_train1,epochs=30,validation_data=(X_validation_s,y_validation))

Epoch 1/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 1.0278 - mean_absolute_error: 0.7162 - val_loss: 0.5038 - val_mean_absolute_error: 0.5040
Epoch 2/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4637 - mean_absolute_error: 0.4876 - val_loss: 0.4470 - val_mean_absolute_error: 0.4783
Epoch 3/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4178 - mean_absolute_error: 0.4630 - val_loss: 0.4270 - val_mean_absolute_error: 0.4633
Epoch 4/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4186 - mean_absolute_error: 0.4605 - val_loss: 0.4186 - val_mean_absolute_error: 0.4508
Epoch 5/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3968 - mean_absolute_error: 0.4533 - val_loss: 0.4014 - val_mean_absolute_error: 0.4415
Epoch 6/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3894 - mean_absolute_error: 0.4416 - val_loss: 0.4098 - val_mean_absolute_error: 0.4602
Epoch 7/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3841 - mean_absolute_error: 0.4403 - v

evaluate

In [ ]:
model.evaluate(X_test_s,y_test,verbose=0)

[0.33149880170822144, 0.3995210528373718]

In [ ]:
x3=X_test_s[1:5]
x3.shape

(4, 8)

predict

In [ ]:
model.predict(x3).round(3)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step


array([[2.36 ],
       [1.861],
       [2.85 ],
       [2.21 ]], dtype=float32)

In [ ]:
y_test[1:5]

array([2.271, 1.629, 2.374, 2.347])

In [ ]:
X_train0.shape[1:]

(8,)

functional API

In [ ]:
input_=keras.layers.Input(shape=X_train1.shape[1:])
hidden_layer1=keras.layers.Dense(50,activation="relu")(input_)
hidden_layer2=keras.layers.Dense(10,activation="relu")(hidden_layer1)
concatenate_layer=keras.layers.Concatenate()([input_,hidden_layer2])
output=keras.layers.Dense(1)(concatenate_layer)
model=keras.Model(inputs=[input_],outputs=[output])




In [ ]:
model.compile(loss="mean_squared_error",
              optimizer="sgd",
              metrics=["mean_absolute_error"]
              )

In [ ]:
model.fit(X_train_s,y_train1,epochs=30,validation_data=(X_validation_s,y_validation))

Epoch 1/30


/usr/local/lib/python3.11/dist-packages/keras/src/models/functional.py:237: UserWarning: The structure of `inputs` doesn't match the expected structure.
Expected: ['keras_tensor_4']
Received: inputs=Tensor(shape=(None, 8))
  warnings.warn(msg)


363/363 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 1.4074 - mean_absolute_error: 0.7837 - val_loss: 0.5454 - val_mean_absolute_error: 0.5359
Epoch 2/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.5322 - mean_absolute_error: 0.5079 - val_loss: 0.4911 - val_mean_absolute_error: 0.5020
Epoch 3/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4694 - mean_absolute_error: 0.4897 - val_loss: 0.4701 - val_mean_absolute_error: 0.4803
Epoch 4/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.4562 - mean_absolute_error: 0.4841 - val_loss: 0.4430 - val_mean_absolute_error: 0.4737
Epoch 5/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.4197 - mean_absolute_error: 0.4688 - val_loss: 0.4302 - val_mean_absolute_error: 0.4721
Epoch 6/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4230 - mean_absolute_error: 0.4576 - val_loss: 0.4121 - val_mean_absolute_error: 0.4577
Epoch 7/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4009 - mean_absolute_error: 0.4485 - val_loss: 0.

In [ ]:
model.evaluate(X_test_s,y_test,verbose=0)

[0.33252397179603577, 0.39794719219207764]

In [ ]:
x3=X_test_s[1:5]
x3.shape

(4, 8)

In [ ]:
model.predict(x3).round(3)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step


array([[2.205],
       [3.137],
       [2.035],
       [4.   ]], dtype=float32)

In [ ]:
y_test[1:5]

array([2.544, 3.042, 2.044, 4.127])

functional API with 2 inputs

In [6]:
X_train_s_1,X_train_s_2=X_train_s[:,:6],X_train_s[:,-4:]
X_validation_s_1,X_validation_s_2=X_validation_s[:,:6],X_validation_s[:,-4:]
X_test_s_1,X_test_s_2=X_test_s[:,:6],X_test_s[:,-4:]

In [7]:
input_1=keras.layers.Input(shape=[6])
input_2=keras.layers.Input(shape=[4])

hidden_layer1=keras.layers.Dense(50,activation="relu")(input_1)
hidden_layer2=keras.layers.Dense(10,activation="relu")(hidden_layer1)
concatenate_layer=keras.layers.Concatenate()([input_2,hidden_layer2])
output=keras.layers.Dense(1)(concatenate_layer)
model=keras.Model(inputs=[input_1,input_2],outputs=[output])




In [ ]:
model.compile(loss="mean_squared_error",
              optimizer="sgd",
              metrics=["mean_absolute_error"]
              )

In [ ]:
model.fit((X_train_s_1,X_train_s_2),y_train1,epochs=30,validation_data=((X_validation_s_1,X_validation_s_2),y_validation))

Epoch 1/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 2.0744 - mean_absolute_error: 0.8835 - val_loss: 0.4753 - val_mean_absolute_error: 0.4950
Epoch 2/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4876 - mean_absolute_error: 0.5089 - val_loss: 0.4349 - val_mean_absolute_error: 0.4700
Epoch 3/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4211 - mean_absolute_error: 0.4711 - val_loss: 0.4131 - val_mean_absolute_error: 0.4588
Epoch 4/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4074 - mean_absolute_error: 0.4648 - val_loss: 0.4038 - val_mean_absolute_error: 0.4558
Epoch 5/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3928 - mean_absolute_error: 0.4603 - val_loss: 0.3982 - val_mean_absolute_error: 0.4492
Epoch 6/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3660 - mean_absolute_error: 0.4442 - val_loss: 0.3931 - val_mean_absolute_error: 0.4432
Epoch 7/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.3856 - mean_absolute_error: 0.4518 - v

#wide and deep network with several output


In [8]:
input_1=keras.layers.Input(shape=[6])
input_2=keras.layers.Input(shape=[4])

hidden_layer1=keras.layers.Dense(50,activation="relu")(input_1)
hidden_layer2=keras.layers.Dense(10,activation="relu")(hidden_layer1)
concatenate_layer=keras.layers.Concatenate()([input_2,hidden_layer2])
output=keras.layers.Dense(1,name="output")(concatenate_layer)
helper_output=keras.layers.Dense(1,name="helper_output")(hidden_layer2)
model_f=keras.Model(inputs=[input_1,input_2],outputs=[output,helper_output])


In [9]:
model_f.compile(loss=["mse","mse"],
              loss_weights=[0.8,0.2],
              optimizer="sgd",
              metrics=["mean_absolute_error","mae"]
              )

In [10]:
model_f.fit((X_train_s_1,X_train_s_2),(y_train1,y_train1),epochs=30,validation_data=((X_validation_s_1,X_validation_s_2),(y_validation,y_validation)))

Epoch 1/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - helper_output_loss: 2.4057 - helper_output_mae: 1.1312 - loss: 1.8884 - output_loss: 1.7591 - output_mean_absolute_error: 0.9403 - val_helper_output_loss: 0.5892 - val_helper_output_mae: 0.5668 - val_loss: 0.5307 - val_output_loss: 0.5160 - val_output_mean_absolute_error: 0.5318
Epoch 2/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - helper_output_loss: 0.6341 - helper_output_mae: 0.5756 - loss: 0.5573 - output_loss: 0.5382 - output_mean_absolute_error: 0.5367 - val_helper_output_loss: 0.5600 - val_helper_output_mae: 0.5590 - val_loss: 0.4944 - val_output_loss: 0.4779 - val_output_mean_absolute_error: 0.5189
Epoch 3/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - helper_output_loss: 0.6167 - helper_output_mae: 0.5705 - loss: 0.5635 - output_loss: 0.5502 - output_mean_absolute_error: 0.5268 - val_helper_output_loss: 0.5448 - val_helper_output_mae: 0.5385 - val_loss: 0.4790 - val_output_loss: 0.4625 - val_output_mean_absolute_error: 0.4

#Subclass API


In [11]:
class WideAndDeepANN(keras.Model):
  def __init__(self,activation="relu",**kwargs):
    super().__init__(**kwargs)
    self.hidden_layer_1=keras.layers.Dense(50,activation=activation)
    self.hidden_layer_2=keras.layers.Dense(10,activation=activation)
    self.final_output=keras.layers.Dense(1)
    self.helper_output=keras.layers.Dense(1)

  def call(self,inputs):
    input_1,input_2=inputs
    h1_out=self.hidden_layer_1(input_1)
    h2_out=self.hidden_layer_2(h1_out)
    concat_out=keras.layers.concatenate([input_2, h2_out])
    final_out=self.final_output(concat_out)
    helper_out=self.helper_output(h2_out)
    return final_out , helper_out





In [12]:
model_sub=WideAndDeepANN()

In [13]:
model_sub.compile(loss=["mse","mse"],
              loss_weights=[0.8,0.2],
              optimizer="sgd",
              metrics=["mean_absolute_error","mae"]
              )

In [14]:
model_sub.fit((X_train_s_1,X_train_s_2),(y_train1,y_train1),epochs=30,validation_data=((X_validation_s_1,X_validation_s_2),(y_validation,y_validation)))

Epoch 1/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 1.8974 - mae: 0.9899 - mean_absolute_error: 0.8736 - mse_loss: 1.9376 - val_loss: 0.6037 - val_mae: 0.5760 - val_mean_absolute_error: 0.5691 - val_mse_loss: 0.6191
Epoch 2/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 1.0658 - mae: 0.5805 - mean_absolute_error: 0.5781 - mse_loss: 0.6233 - val_loss: 0.4958 - val_mae: 0.5538 - val_mean_absolute_error: 0.5136 - val_mse_loss: 0.5576
Epoch 3/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.5993 - mae: 0.5564 - mean_absolute_error: 0.5206 - mse_loss: 0.5743 - val_loss: 0.4682 - val_mae: 0.5320 - val_mean_absolute_error: 0.4878 - val_mse_loss: 0.5293
Epoch 4/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4930 - mae: 0.5343 - mean_absolute_error: 0.4973 - mse_loss: 0.5413 - val_loss: 0.4511 - val_mae: 0.5297 - val_mean_absolute_error: 0.4819 - val_mse_loss: 0.5171
Epoch 5/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4512 - mae: 0.5268 - mean_absolute_error: 

#saving Model

In [ ]:
model_f.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)  │ (None, 6)              │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_9 (Dense)           │ (None, 50)             │            350 │ input_layer[0][0]      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ input_layer_1             │ (None, 4)              │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_10 (Dense)          │ (None, 10)             │            510 │ dense_9[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ concatenate_4             │ (None, 14)             │              0 │ input_layer_1[0][0],   │
│ (Concatenate)             │                        │                │ dense_10[0][0]         │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ output (Dense)            │ (None, 1)              │             15 │ concatenate_4[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ helper_output (Dense)     │ (None, 1)              │             11 │ dense_10[0][0]         │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 888 (3.47 KB)

 Trainable params: 886 (3.46 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

In [15]:
model_f.save("housing_reg_model_f.keras")

In [16]:
model_f_reg=keras.models.load_model("housing_reg_model_f.keras")

In [ ]:
model_f_reg.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)  │ (None, 6)              │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_9 (Dense)           │ (None, 50)             │            350 │ input_layer[0][0]      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ input_layer_1             │ (None, 4)              │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_10 (Dense)          │ (None, 10)             │            510 │ dense_9[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ concatenate_4             │ (None, 14)             │              0 │ input_layer_1[0][0],   │
│ (Concatenate)             │                        │                │ dense_10[0][0]         │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ output (Dense)            │ (None, 1)              │             15 │ concatenate_4[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ helper_output (Dense)     │ (None, 1)              │             11 │ dense_10[0][0]         │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 1,774 (6.93 KB)

 Trainable params: 886 (3.46 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 888 (3.47 KB)

In [17]:
model_sub.save_weights("housing_reg_model_sub.weights.h5")

In [18]:
model_sub_reg=keras.models.load_model("housing_reg_model_sub.weights.h5")

ValueError: No model config found in the file at housing_reg_model_sub.weights.h5.

In [ ]:
model_sub.summary()

Model: "wide_and_deep_ann_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_11 (Dense)                     │ (None, 50)                  │             350 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_12 (Dense)                     │ (None, 10)                  │             510 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_13 (Dense)                     │ (None, 1)                   │              15 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_14 (Dense)                     │ (None, 1)                   │              11 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 888 (3.47 KB)

 Trainable params: 886 (3.46 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

#Callback

In [25]:
model_checkpoint_callback = keras.callbacks.ModelCheckpoint("model_Cb_reg_housing.h5",
    save_best_only=True)
model_earlystopping_callback=keras.callbacks.EarlyStopping(patience=5,restore_best_weights=True)


In [27]:
model_f.fit((X_train_s_1,X_train_s_2),(y_train1,y_train1),epochs=30,validation_data=((X_validation_s_1,X_validation_s_2),(y_validation,y_validation)),
            callbacks=[model_checkpoint_callback,model_earlystopping_callback])

Epoch 1/30
357/363 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - helper_output_loss: 0.4226 - helper_output_mae: 0.4717 - loss: 0.3664 - output_loss: 0.3524 - output_mean_absolute_error: 0.4275

363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - helper_output_loss: 0.4224 - helper_output_mae: 0.4716 - loss: 0.3663 - output_loss: 0.3523 - output_mean_absolute_error: 0.4274 - val_helper_output_loss: 0.4054 - val_helper_output_mae: 0.4606 - val_loss: 0.3491 - val_output_loss: 0.3349 - val_output_mean_absolute_error: 0.4142
Epoch 2/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - helper_output_loss: 0.4334 - helper_output_mae: 0.4748 - loss: 0.3777 - output_loss: 0.3638 - output_mean_absolute_error: 0.4309 - val_helper_output_loss: 0.4061 - val_helper_output_mae: 0.4620 - val_loss: 0.3502 - val_output_loss: 0.3361 - val_output_mean_absolute_error: 0.4148
Epoch 3/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - helper_output_loss: 0.4319 - helper_output_mae: 0.4723 - loss: 0.3778 - output_loss: 0.3643 - output_mean_absolute_error: 0.4292 - val_helper_output_loss: 0.4073 - val_helper_output_mae: 0.4650 - val_loss: 0.3521 - val_output_loss: 0.3382 - val_output_mean_absolute_error: 0.4184
Epoch 4/3

363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - helper_output_loss: 0.4004 - helper_output_mae: 0.4642 - loss: 0.3464 - output_loss: 0.3329 - output_mean_absolute_error: 0.4187 - val_helper_output_loss: 0.4031 - val_helper_output_mae: 0.4598 - val_loss: 0.3479 - val_output_loss: 0.3340 - val_output_mean_absolute_error: 0.4130
Epoch 6/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - helper_output_loss: 0.4238 - helper_output_mae: 0.4711 - loss: 0.3722 - output_loss: 0.3592 - output_mean_absolute_error: 0.4285 - val_helper_output_loss: 0.4132 - val_helper_output_mae: 0.4631 - val_loss: 0.3560 - val_output_loss: 0.3415 - val_output_mean_absolute_error: 0.4147
Epoch 7/30
363/363 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - helper_output_loss: 0.4089 - helper_output_mae: 0.4662 - loss: 0.3589 - output_loss: 0.3464 - output_mean_absolute_error: 0.4249 - val_helper_output_loss: 0.4090 - val_helper_output_mae: 0.4622 - val_loss: 0.3537 - val_output_loss: 0.3398 - val_output_mean_absolute_error: 0.4129
Epoch 8/3

In [28]:
class Mycallback(keras.callbacks.Callback):
  def on_train_end(self,logs=None):
    print("")
  def on_epoch_end(self,epoch,logs):
    print(logs["val_loss"])

In [29]:
mycb=Mycallback()